networks:
  crypto-net:
    driver: bridge

services:
  app:
    build: .
    container_name: liquidation-tracker-app
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - crypto-net
    env_file:
      - .env
    environment:
      - TZ=Europe/Kyiv
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: liquidation-tracker-redis
    restart: unless-stopped
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - crypto-net
